"""Track summarized messages

Revision ID: 2277092ad123
Revises: cbe5a7c0865a
Create Date: 2026-10-06 15:56:38.190537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2277092ad123'
down_revision: Union[str, Sequence[str], None] = 'cbe5a7c0865a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "conversation",
    sa.Column(
        "summary_message_count",
        sa.Integer(),
        server_default=sa.text("0"),
        nullable=False,
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'summary_message_count')
    # ### end Alembic commands ###
